name: reviewdog

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
