name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: bundle install
        run: |
          bundle install
      - name: run test
        run: |
          bundle exec ruby test/test_sample.rb
